
set_blocked_apps:
  description: Set the blocked apps for a profile.
  fields:
    blocked_apps:
      description: (Required) List of apps to block. Passing an empty list will unblock all supported apps.
      example: netflix
    target_profile:
      description: (Optional) Name(s) or ID(s) of profile(s) to set. Defaults to all profiles if not specified.
      example: John Doe or 1234567
    target_network:
      description: (Optional) Name(s) or ID(s) of network(s) in which desired profile(s) are located. Defaults to all networks if not specified.
      example: My Network or 1234567    

set_nightlight_mode:
  description: Set the nightlight mode for an Eero Beacon device.
  fields:
    mode:
      description: (Required) Target mode for the nightlight. Valid modes are "disabled", "ambient", or "schedule".
      example: "ambient"
    time_on:
      description: (Optional) Scheduled time for the nightlight to turn on. Only applicable if "mode" is set to "schedule". Required format is "HH:MM".
      example: "20:00"
    time_off:
      description: (Optional) Scheduled time for the nightlight to turn off. Only applicable if "mode" is set to "schedule". Required format is "HH:MM".
      example: "06:00"
    target_eero:
      description: (Optional) Name(s) or ID(s) of Eero Beacon device(s) to set. Defaults to all Eero Beacon devices if not specified.
      example: Living Room or 1234567
    target_network:
      description: (Optional) Name(s) or ID(s) of network(s) in which desired Eero Beacon device(s) are located. Defaults to all networks if not specified.
      example: My Network or 1234567
