- id: "1636311624815"
  alias: Encender garaje
  description: Encender sonoff switch cuando detecte movimiento
  trigger:
    - type: motion
      platform: device
      device_id: 2adecd4de0ca89ea9b049286c91f8042
      entity_id: binary_sensor.motion_sensor
      domain: binary_sensor
  condition: []
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.sonoff_1000c1dbb0
  mode: restart
- id: "1636311769143"
  alias: Apagar garaje
  description: Apagar luz cuando no detecte movimiento
  trigger:
    - type: no_motion
      platform: device
      device_id: 2adecd4de0ca89ea9b049286c91f8042
      entity_id: binary_sensor.motion_sensor
      domain: binary_sensor
      for:
        hours: 0
        minutes: 0
        seconds: 30
        milliseconds: 0
  condition: []
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.sonoff_1000c1dbb0
  mode: restart
- id: "1639246553873"
  alias: Dehumidifier on
  description: ""
  trigger:
    - platform: time
      at: 00:40:00
  condition:
    - type: is_humidity
      condition: device
      device_id: 46e1355a193ec22e4bf1d372a9562bcc
      entity_id: sensor.hall_humidity
      domain: sensor
      above: 50
  action:
    - type: turn_on
      device_id: 76a2b476cd597555ec19abe52d0dfb85
      entity_id: switch.dehumidifier
      domain: switch
  mode: single
- id: "1639246608141"
  alias: Dehumidifier off
  description: ""
  trigger:
    - platform: time
      at: 04:30
  condition: []
  action:
    - type: turn_off
      device_id: 76a2b476cd597555ec19abe52d0dfb85
      entity_id: switch.dehumidifier
      domain: switch
  mode: single
- id: "1639932833502"
  alias: Pasillo on
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 02e66fb83767c9a06bca53f3da7946eb
      entity_id: binary_sensor.presence_7
      domain: binary_sensor
  condition:
    - type: is_illuminance
      condition: device
      device_id: 02e66fb83767c9a06bca53f3da7946eb
      entity_id: sensor.pirpasillo
      domain: sensor
      below: 25
  action:
    - type: turn_on
      device_id: fc2cc2bb38a44b2e571bb19a480689fc
      entity_id: light.lampara_pasillo
      domain: light
  mode: single
- id: "1639933978425"
  alias: Pasillo off
  description: ""
  trigger:
    - type: no_motion
      platform: device
      device_id: 02e66fb83767c9a06bca53f3da7946eb
      entity_id: binary_sensor.presence_7
      domain: binary_sensor
      for:
        hours: 0
        minutes: 0
        seconds: 0
  condition: []
  action:
    - type: turn_off
      device_id: fc2cc2bb38a44b2e571bb19a480689fc
      entity_id: light.lampara_pasillo
      domain: light
  mode: restart
- id: "1639938167833"
  alias: Cocina on
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 1d6f6eb056c0f58e3a752f25a3eb6f87
      entity_id: binary_sensor.presence_5
      domain: binary_sensor
  condition:
    - condition: device
      type: is_off
      device_id: deebabd24806abcb44a768baa5c0edbc
      entity_id: light.foco_1
      domain: light
    - condition: device
      type: is_off
      device_id: 7d8d2d5fc604b73ee96c7da7e2dd18a8
      entity_id: light.foco_10
      domain: light
    - type: is_illuminance
      condition: device
      device_id: 1d6f6eb056c0f58e3a752f25a3eb6f87
      entity_id: sensor.pircocina
      domain: sensor
      below: 15
  action:
    - service: light.turn_on
      target:
        area_id: cocina
      data:
        brightness_pct: 85
  mode: single
- id: "1639938277341"
  alias: Cocina off
  description: ""
  trigger:
    - type: no_motion
      platform: device
      device_id: 1d6f6eb056c0f58e3a752f25a3eb6f87
      entity_id: binary_sensor.presence_5
      domain: binary_sensor
      for:
        hours: 0
        minutes: 10
        seconds: 0
  condition: []
  action:
    - service: light.turn_off
      target:
        area_id: cocina
      data: {}
  mode: restart
- id: "1639955024106"
  alias: Sacar basuras
  description: ""
  trigger:
    - platform: time
      at: "19:00"
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ state_attr('sensor.ics_1', 'remaining') == 1 }}"
        - condition: template
          value_template: "{{ state_attr('sensor.ics_2', 'remaining') == 1 }}"
        - condition: template
          value_template: "{{ state_attr('sensor.ics_3', 'remaining') == 1 }}"
  action:
    - service: script.mensaje_recogida_de_basura
  mode: single
- id: "1640033120388"
  alias: Nicolas window open, climate off
  description: ""
  use_blueprint:
    path: SmartLiving-Rocks/tado.yaml
    input:
      window_entity: binary_sensor.nicolas_open_window_2
      climate_target: climate.nicolas_2
- id: "1640033671378"
  alias: Salon window open, climate off
  description: ""
  use_blueprint:
    path: SmartLiving-Rocks/tado.yaml
    input:
      window_entity: binary_sensor.salon_open_window
      climate_target: climate.salon
- id: "1643485768145"
  alias: Zapatero on
  description: ""
  trigger:
    - type: opened
      platform: device
      device_id: 9abd4889b726ee7cca3c97ca00f1aefa
      entity_id: binary_sensor.puerta_zapatero
      domain: binary_sensor
  condition: []
  action:
    - type: turn_on
      device_id: d9dae8c65a3014a24186c1f8b1628033
      entity_id: light.lampara_zapatero
      domain: light
  mode: single
- id: "1643485856862"
  alias: Zapatero off
  description: ""
  trigger:
    - type: not_opened
      platform: device
      device_id: 9abd4889b726ee7cca3c97ca00f1aefa
      entity_id: binary_sensor.puerta_zapatero
      domain: binary_sensor
  condition: []
  action:
    - type: turn_off
      device_id: d9dae8c65a3014a24186c1f8b1628033
      entity_id: light.lampara_zapatero
      domain: light
  mode: single
- id: "1644487062091"
  alias: Radiator off
  description: ""
  trigger:
    - type: temperature
      platform: device
      device_id: 34b6faa0cd59d3ec8ffb82337a27e6a0
      entity_id: sensor.temperaturastudy
      domain: sensor
      above: 20
  condition: []
  action:
    - type: turn_off
      device_id: 3ef8cef9cb3eaeb0f5cab527b53df55f
      entity_id: switch.radiador
      domain: switch
  mode: single
- id: "1660509857617"
  alias: Charger on
  description: ""
  trigger:
    - platform: time
      at: 00:40:00
  condition: []
  action:
    - type: turn_on
      device_id: 404f086e6d548d9fd67b1d52cca7c0ab
      entity_id: switch.psl_217243_charging_allowed
      domain: switch
  mode: single
- id: "1660509959391"
  alias: Charger off
  description: ""
  trigger:
    - platform: time
      at: 04:20:00
  condition: []
  action:
    - type: turn_off
      device_id: 404f086e6d548d9fd67b1d52cca7c0ab
      entity_id: switch.psl_217243_charging_allowed
      domain: switch
  mode: single
- id: "1663529667041"
  alias: Buzon opened
  description: Manda mensaje cuando el buzón se abre
  trigger:
    - type: opened
      platform: device
      device_id: 842ec6b5af079136c71f0a24092e3633
      entity_id: binary_sensor.buzon
      domain: binary_sensor
  condition: []
  action:
    - service: notify.notify
      data:
        title: Correo nuevo
        message: Se ha abierto el buzón
  mode: single
- id: "1667654894255"
  alias: Secadora is running
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.secadora_current
      for:
        hours: 0
        minutes: 1
        seconds: 0
      above: 1
  condition:
    - condition: state
      entity_id: input_select.secadora
      state: "Off"
  action:
    - service: input_select.select_option
      data:
        option: Running
      target:
        entity_id: input_select.secadora
  mode: single
- id: "1667663870145"
  alias: Secadora unemptied
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.secadora_current
      for:
        hours: 0
        minutes: 1
        seconds: 0
      below: 0.1
  condition:
    - condition: state
      entity_id: input_select.secadora
      state: Running
  action:
    - service: notify.notify
      data:
        title: " \U0001F455 Secadora terminada"
        message: Ya puedes sacar la ropa
    - service: input_select.select_option
      data:
        option: Unemptied
      target:
        entity_id: input_select.secadora
  mode: single
- id: "1667664298296"
  alias: Secadora off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.puerta_secadora
      from: "off"
      to: "on"
  condition: []
  action:
    - service: input_select.select_option
      data:
        option: "Off"
      target:
        entity_id: input_select.secadora
  mode: single
- id: "1667672381001"
  alias: Lavadora running
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.lavadora_current
      for:
        hours: 0
        minutes: 1
        seconds: 0
      above: 0.2
  condition:
    - condition: state
      entity_id: input_select.lavadora
      state: "Off"
  action:
    - service: input_select.select_option
      data:
        option: Running
      target:
        entity_id: input_select.lavadora
  mode: single
- id: "1667672844112"
  alias: Lavadora unemptied
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.lavadora_current
      for:
        hours: 0
        minutes: 3
        seconds: 0
      below: 0.2
  condition:
    - condition: state
      entity_id: input_select.lavadora
      state: Running
  action:
    - service: notify.notify
      data:
        title: "\U0001F455 Lavadora acabada"
        message: La ropa esta limpia
    - service: input_select.select_option
      data:
        option: Unemptied
      target:
        entity_id: input_select.lavadora
  mode: single
- id: "1667673340764"
  alias: Lavadora off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.puerta_lavadora
      from: "off"
      to: "on"
  condition: []
  action:
    - service: input_select.select_option
      data:
        option: "Off"
      target:
        entity_id: input_select.lavadora
  mode: single
- id: "1670088596974"
  alias: Xmas on
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 0
  condition: []
  action:
    - type: turn_on
      device_id: 3ef8cef9cb3eaeb0f5cab527b53df55f
      entity_id: switch.radiador
      domain: switch
    - type: turn_on
      device_id: 500b6b3eab17ab692e709c0ac21efe01
      entity_id: switch.enchufe_jardin_outlet_3
      domain: switch
  mode: single
- id: "1670088735260"
  alias: Xmas off
  description: ""
  trigger:
    - platform: time
      at: "20:15:00"
  condition: []
  action:
    - type: turn_off
      device_id: 3ef8cef9cb3eaeb0f5cab527b53df55f
      entity_id: switch.radiador
      domain: switch
    - type: turn_off
      device_id: 500b6b3eab17ab692e709c0ac21efe01
      entity_id: switch.enchufe_jardin_outlet_3
      domain: switch
  mode: single
- id: "1672871319378"
  alias: Camera thumbnail
  description:
    Capture Image on Trigger, Send Mobile Notification with Actions, Snooze
    or Alarm via Actions
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.presence_7
      to: "on"
      id: sensor
    - platform: event
      event_type: mobile_app_notification_action
      id: snooze
      event_data:
        action: SNOOZE
    - platform: event
      event_type: mobile_app_notification_action
      id: alarm
      event_data:
        action: ALARM
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: sensor
          sequence:
            - service: eufy_security.start_rtsp_livestream
              data: {}
            - service: eufy_security.stop_rtsp_livestream
              data: {}
            - service: notify.mobile_app_iphone_160
              data:
                message: Motion detected
                data:
                  image: /api/camera_proxy/camera.entryway
                  actions:
                    - action: ALARM
                      title: Alarm
                    - action: SNOOZE
                      title: Snooze
        - conditions:
            - condition: trigger
              id: snooze
          sequence:
            - service: eufy_security.snooze
              data:
                snooze_time: 10
                snooze_chime: false
                snooze_motion: true
                snooze_homebase: false
              target:
                entity_id: camera.entryway
        - conditions:
            - condition: trigger
              id: alarm
          sequence:
            - service: alarm_control_panel.alarm_trigger
              data: {}
              target:
                entity_id: alarm_control_panel.entryway
  mode: single
- id: "1686850527116"
  alias: Charging on
  description: ""
  trigger:
    - platform: time
      at: 00:40:00
  condition:
    - type: is_plugged_in
      condition: device
      device_id: e6998c098b392712f3f1dbcee7583c5a
      entity_id: binary_sensor.psl_217243_cable_status
      domain: binary_sensor
  action: []
  mode: single
- id: "1686850579502"
  alias: Charging off
  description: ""
  trigger:
    - platform: time
      at: 04:20:00
  condition: []
  action:
    - type: turn_off
      device_id: e6998c098b392712f3f1dbcee7583c5a
      entity_id: switch.psl_217243_charging_allowed
      domain: switch
  mode: single
- id: "1691782131812"
  alias: Conversation agent agenda notification
  description: ""
  use_blueprint:
    path: homeassistant/notify_agent_agenda.yaml
    input:
      conversation_agent: 954bac824c80252069a65938b6afb1cb
      weather_entity: weather.met_office_sawston_3_hourly
      zone_entity: zone.home
      calendar_entity: calendar.podorricalendar
      notify_service: notify.mobile_app_macbookpro
      media_player:
        entity_id: media_player.salon
        media_content_id: media-source://tts/tts.piper?message=Hello+David%2C+you+can+play+any+text+on+any+supported+media+player%21&language=en_US&voice=en_US-amy-low
        media_content_type: provider
        metadata:
          title: Hello David, you can play any text on any supported media player!
          thumbnail: https://brands.home-assistant.io/_/tts/logo.png
          media_class: app
          children_media_class:
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://tts
            - media_content_type: provider
              media_content_id: media-source://tts/tts.piper?message=Hello+David%2C+you+can+play+any+text+on+any+supported+media+player%21&language=en_US&voice=en_US-amy-low
