---
# Welcome to my Home Assistant configuration!
#
homeassistant:
  # Load packages
  packages: !include_dir_named integrations

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
