---
# Welcome to my Home Assistant configuration!
#
homeassistant:
  # Load packages
  packages: !include_dir_named integrations

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
automation old: !include_dir_merge_list automations
